pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Finalizare') {
            steps {
                echo "Acest branch este pentru finalizare"
            }
        }  
    }
}
